BEGIN TRANSACTION;
CREATE TABLE clientes (id INTEGER PRIMARY KEY AUTOINCREMENT, apellido TEXT NOT NULL, nombre TEXT NOT NULL, direccion TEXT, telefono TEXT );
INSERT INTO "clientes" VALUES(1,'Zeller','Esteban Javier',NULL,NULL);
CREATE TABLE `autos` ( `patente` TEXT PRIMARY KEY, `id_dueno` INTEGER REFERENCES `clientes`(`id`), `marca` text NOT NULL, `modelo` text, `ano` TEXT default NULL, `color` text );
CREATE TABLE `presupuesto` ( `id_presupuesto` INTEGER PRIMARY KEY AUTOINCREMENT, `fecha` TEXT NOT NULL, `kilometraje` INTEGER NOT NULL, `id_auto` TEXT REFERENCES `autos`(`patente`), `titulo` text, `contenido` blob, `creado` text NOT NULL, `modificado` TEXT , `imprimir` INTEGER, `email` INTEGER );
INSERT INTO "presupuesto" VALUES(23,'242424',2434234,'1','321312312','123123123','13123123','2312312',2,2);
INSERT INTO "autos" VALUES('adf142',1,'sdasda','asdasd','NULLasdasd','asdsad');
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('presupuesto',1);
INSERT INTO "sqlite_sequence" VALUES('clientes',1);
COMMIT;