BEGIN TRANSACTION;
CREATE TABLE categoria (id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, descripcion TEXT);
CREATE TABLE clientes (id INTEGER PRIMARY KEY AUTOINCREMENT, apellido TEXT NOT NULL, nombre TEXT NOT NULL, direccion TEXT, telefono TEXT);
CREATE TABLE producto (id INTEGER PRIMARY KEY AUTOINCREMENT, id_categoria NUMERIC, nombre TEXT, precio_venta NUMERIC, descripcion BLOB, marca TEXT);
CREATE TABLE recibos ( id INTEGER PRIMARY KEY AUTOINCREMENT, cliente TEXT, num_mes INTEGER,  texto TEXT, precio NUMBER, fecha_pago TEXT, contado INTEGER, cuenta_corriente INTEGER  );
CREATE TABLE presupuestos_productos ( id INTEGER PRIMARY KEY AUTOINCREMENT, id_presupuesto INTEGER NOT NULL, id_producto INTEGER NOT NULL, cantidad NUMERIC );
CREATE TABLE presupuestos ( id INTEGER PRIMARY KEY AUTOINCREMENT, destinatario TEXT NOT NULL, fecha TEXT NOT NULL, total NUMERIC, contenido BLOB );
CREATE TABLE car_categorias ( id_categoria INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL );
CREATE TABLE car_establecimientos ( id_establecimiento INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT NOT NULL, respma TEXT NOT NULL );
CREATE TABLE car_caravana ( id_caravana INTEGER PRIMARY KEY AUTOINCREMENT, codigo TEXT NOT NULL UNIQUE );
CREATE TABLE car_tri( id_tri INTEGER PRIMARY KEY AUTOINCREMENT, dta TEXT NOT NULL, razon NUMERIC NOT NULL,fecha TEXT NOT NULL, id_categoria NUMERIC NOT NULL, id_estab_destino NUMERIC, id_estab_origen NUMERIC, id_comprador NUMERIC, id_vendedor NUMERIC );
CREATE TABLE car_carv_tri( id_caravana INTEGER, id_tri, PRIMARY KEY( id_caravana, id_tri ) );
INSERT INTO sqlite_sequence VALUES ( 'car_tri', '1' );
INSERT INTO sqlite_sequence VALUES ( 'car_categorias', '1' );
INSERT INTO sqlite_sequence VALUES ( 'car_establecimientos', '1' );
INSERT INTO sqlite_sequence VALUES ( 'car_caravana', '1' );
INSERT INTO sqlite_sequence VALUES ( 'car_carav_tri', '1' );
INSERT INTO sqlite_sequence VALUES ( 'categoria', '1' );
INSERT INTO sqlite_sequence VALUES ( 'clientes', '1' );
INSERT INTO sqlite_sequence VALUES ( 'producto', '1' );
INSERT INTO sqlite_sequence VALUES ( 'recibos', '1' );
COMMIT;
