CREATE TABLE IF NOT EXISTS categoria ( id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, descripcion TEXT , tipo INTEGER);
CREATE TABLE IF NOT EXISTS compras ( id INTEGER PRIMARY KEY AUTOINCREMENT,id_proveedor NUMERIC , fecha TEXT  );
CREATE TABLE IF NOT EXISTS compras_productos ( id INTEGER PRIMARY KEY AUTOINCREMENT, id_compra NUMERIC , id_producto NUMERIC  , precio_compra NUMERIC , cantidad NUMERIC  );
CREATE TABLE IF NOT EXISTS dueno ( id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT , apellido TEXT , direccion BLOB, email TEXT, telefono_celular TEXT, telefono_linea TEXT);
CREATE TABLE IF NOT EXISTS mascota (id INTEGER PRIMARY KEY AUTOINCREMENT, id_dueno NUMERIC , nombre TEXT , raza TEXT, genero TEXT );
CREATE TABLE IF NOT EXISTS proveedor ( id INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT , direccion BLOB, email TEXT, fax TEXT, telefono_celular TEXT, telefono_linea TEXT, cuit_cuil TEXT );
CREATE TABLE IF NOT EXISTS peluqueria ( id INTEGER PRIMARY KEY AUTOINCREMENT, id_mascota INTEGER, descripcion TEXT, precio INTEGER, fecha TEXT );
CREATE TABLE IF NOT EXISTS ventas ( id INTEGER PRIMARY KEY AUTOINCREMENT, fecha TEXT );
CREATE TABLE IF NOT EXISTS ventas_productos ( id INTEGER PRIMARY KEY AUTOINCREMENT, id_venta NUMERIC , id_producto NUMERIC , precio NUMERIC , cantidad NUMERIC );
CREATE TABLE IF NOT EXISTS gastos ( id INTEGER PRIMARY KEY AUTOINCREMENT, id_categoria INTEGER, descripcion TEXT, costo INTEGER, fecha TEXT );
CREATE TABLE IF NOT EXISTS producto (id INTEGER PRIMARY KEY, id_categoria NUMERIC, nombre TEXT, precio_venta NUMERIC, descripcion BLOB, marca TEXT, precio_compra NUMERIC);
